security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        api_provider:
            id: App\Security\ApiUserProvider
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        admin_login:
            pattern: ^/api/admin/login$
            stateless: true
            provider: api_provider
            json_login:
                check_path: /api/admin/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        
        client_login:
            pattern: ^/api/client/login$
            stateless: true
            provider: api_provider
            json_login:
                check_path: /api/client/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        
        api:
            pattern: ^/api/
            stateless: true
            provider: api_provider
            jwt: ~
        
        main:
            lazy: true
    
    access_control:
        - { path: ^/api/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/api/client/login$, roles: PUBLIC_ACCESS }
        - { path: ^/api/, roles: [ROLE_ADMIN, ROLE_CLIENT] }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
