controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_client_login:
    path: /api/auth/clients
    methods: [POST]

api_admin_login:
    path: /api/auth/admins
    methods: [POST]
